config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
  get 'friends', to: 'friendships#index'
  get 'search_friends', to: 'friendships#search'
  devise_for :users
  resources :users, only: [:show]
  get 'my_portfolio', to: 'users#my_portfolio'
  get 'search_stocks', to: 'stocks#search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks, dependent: :destroy
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  before_save do
    ticker.upcase!
  end

  def self.look_up(ticker_symbol)
    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.dig(:iex, :iex_publishable_token),
      secret_token: Rails.application.credentials.dig(:iex, :iex_secret_token),
      endpoint: 'https://sandbox.iexapis.com/v1'
    )
    begin
      new(name: client.company(ticker_symbol).company_name,
          ticker: ticker_symbol,
          price: client.price(ticker_symbol)
      )
    rescue
      return nil
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  def self.search(query, current_user)
    query.downcase!
    where('lower(email) LIKE ?', "%#{query}%" )
      .or(where('lower(firstname) LIKE ?', "%#{query}%"))
      .or(where('lower(lastname) LIKE ?', "%#{query}%"))
      .where.not(id: current_user.id)
  end

  def tracked?(ticker)
    stocks.find_by(ticker: ticker.upcase).present?
  end

  def tracked_limit?
    stocks.count > 9
  end

  def full_name
    "#{firstname} #{lastname}"
  end

  def friends?(friend)
    friends.where(id: friend.id).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:firstname, :lastname])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:firstname, :lastname])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def index
    @friends = current_user.friends
  end

  def create
    friendship = current_user.friendships.build(friend_id: params[:friend])
    if friendship.save
      flash.notice = "You are now friends."
    else
      flash.notice = "Something went wrong."
    end
    redirect_to friends_path
  end

  def search
    if params[:friend].present?
      @users = User.search(params[:friend], current_user)
      if @users.present?
        respond_to do |format|
          format.js { render partial: 'friendships/result' }
        end
      else
        respond_to do |format|
          flash.now.alert = "User not found. Check spelling."
          format.js { render partial: 'friendships/result' }
        end
      end
    else
      respond_to do |format|
        flash.now.alert = "Search field can't be blank."
        format.js { render partial: 'friendships/result' }
      end
    end
  end

  def destroy
    friendship = Friendship.find_by(friend_id: params[:id])
    friendship.destroy
    flash.notice = "Friendship removed."
    redirect_to friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  def search
    if params[:ticker].present?
      @stock = Stock.look_up(params[:ticker])
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
      else
        respond_to do |format|
          flash.now.alert = "Invalid ticker symbol."
          format.js { render partial: 'users/result' }
        end
      end
    else
      respond_to do |format|
        flash.now.alert = "Search field can't be blank."
        format.js { render partial: 'users/result' }
      end
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  def create
    stock = Stock.find_by(ticker: params[:ticker])
    if stock
      UserStock.create(user_id: current_user, stock_id: stock)
    else
      stock = Stock.look_up(params[:ticker])
      stock.save
      UserStock.create(user_id: current_user.id, stock_id: stock.id)
    end
    flash.notice = "Stock #{stock.name} succesfully added to your portfolio."
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    userstock = UserStock.find_by(user_id: current_user.id, stock_id: stock.id)
    userstock.destroy
    flash.notice = "#{stock.name} removed from tracked list."
    redirect_to my_portfolio_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks 
  end

  def my_portfolio
    @user = current_user
    @tracked_stocks = current_user.stocks
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/friendships/_result.html.erb
<div style="max-width: 22rem;">
  <%= render 'layouts/messages' %>
</div>

<% if @users %>
  <table class="table table-sm user-search">
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><strong>First name: </strong> <%= user.full_name.titleize %></td>
          <td><strong>Actions: </strong> <%= link_to 'Profile', user_path(user), class: "btn btn-info btn-sm" %></td>
          <% if current_user.friends?(user) %>
            <td><span class="badge badge-warning">Already Friends</span></td>
          <% else %>
            <td><%= link_to 'Follow?', friendships_path(friend: user), method: :post, class: "btn btn-info btn-sm" %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/friendships/_result.js.erb
document.querySelector('#results').innerHTML = '<%= escape_javascript(render 'friendships/result.html') %>'

app/views/friendships/index.html.erb
<h1>Friendships#index</h1>
<p>Find me in app/views/friendships/index.html.erb</p>

<h3>Search Friends</h3>
<%= form_with url: search_friends_path, method: :get, class: "form-inline" do |f| %>
  <%= f.text_field 'friend', placeholder: "Search by name or email", class: "form-control mb-2 mr-sm-2" %>
  <%= f.button type: :submit, class: "btn btn-primary mb-2" do %>
    <%= fa_icon "chevron-right" %>
  <% end %>
<% end %>

<div id="results"></div>

<table class="table table-striped col-sm-10">
  <thead>
    <tr>
      <th scope="col">Firstname</th>
      <th scope="col">Lastname</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= friend.firstname %></td>
        <td><%= friend.lastname %></td>
        <td>
          <%= link_to 'Profile', user_path(friend), class: "btn btn-info btn-sm" %>
          <%= link_to 'Remove Friend', friendship_path(friend), method: :delete, data: { confirm: "Are you sure?" },
                                                                  class: "btn btn-danger btn-sm" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/_messages.html.erb
<% if notice %>
  <div class="alert alert-success notice text-center alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert text-center alert-dismissible fade show" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <%= link_to "Stock Tracker", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'My Portfolio', my_portfolio_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Friends', friends_path, class: 'nav-link', class: 'nav-link' %>
          </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% if user_signed_in? %>
              <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
                <%= fa_icon "edit" %> Edit Account
              <% end %>
              <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            <% else %>
              <%= link_to 'Log In', user_session_path, class: "dropdown-item" %>
              <%= link_to 'Sign Up', new_user_registration_path, class: "dropdown-item" %>
            <% end %>
          </div>
        </li>
      </ul>
      <% if user_signed_in? %>
        <ul class="navbar-nav ml-auto">
          <%= fa_icon "user", class: "nav-item my-2 mr-2" %>
          <% if current_user.firstname || current_user.lastname %>
            <li class="nav-item my-2 ml-auto mr-4"><%= current_user.full_name %></li>
          <% else %>
            <li class='nav-item my-2 mr-4'>Anonymous</li>
          <% end %>
        </ul>
      <% end %>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stock Tracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stocks/_tracked_list.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Ticker</th>
      <th scope="col">Price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @tracked_stocks.each do |stock| %>
      <tr>
        <th scope="row"><%= stock.name %></th>
        <td><%= stock.ticker %></td>
        <td><%= stock.price %></td>
        <td>
          <% if current_user == @user %>
            <%= link_to 'Untrack', user_stock_path(stock), method: :delete, data: { confirm: "Are you sure?"},
                                                           class: 'btn btn-sm btn-danger'  
            %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/stocks/search.html.erb
<h1>Stocks#search</h1>
<p>Find me in app/views/stocks/search.html.erb</p>

app/views/users/_result.html.erb
<div style="max-width: 18rem;">
  <%= render 'layouts/messages' %>
</div>

<% if @stock %>
  <div class="card bg-light mb-3" style="max-width: 18rem;">
    <div class="card-body">
      <strong>Symbol: </strong><p class="card-text"><%= @stock.ticker.upcase %></p>
      <strong>Name: </strong><p class="card-text"><%= @stock.name %></p>
      <strong>Latest Price: </strong><p class="card-text"><%= @stock.price %></p>
      <% if current_user.tracked?(@stock.ticker) %>
        <small class="badge badge-warning">Stock already being tracked</small>
      <% elsif current_user.tracked_limit? %>
        <small class="badge badge-warning">Reached limit for tracked stock.</small>
      <% else %>
        <%= link_to 'Add to Portfolio', user_stocks_path(ticker: @stock.ticker), method: :post, class: "btn btn-outline-success" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= escape_javascript(render 'users/result.html') %>'

app/views/users/my_portfolio.html.erb
<h1>Users#my_portfolio</h1>
<p>Find me in app/views/users/my_portfolio.html.erb</p>

<h3>Search Stocks</h3>

<%= form_with url: search_stocks_path, method: :get, class: "form-inline" do |f| %>
  <%= f.text_field 'ticker', class: "form-control mb-2 mr-sm-2" %>
  <%= f.button type: :submit, class: "btn btn-primary mb-2" do %>
    <%= fa_icon "chevron-right" %>
  <% end %>
<% end %>

<div id="results"></div>

<% if @tracked_stocks.present? %>
  <%= render 'stocks/tracked_list' %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.full_name %>'s Page</h1>

<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @user.full_name %></h5>
    <% if current_user.friends?(@user) %>
      <td><span class="badge badge-warning">Already Friends</span></td>
    <% else %>
      <td><%= link_to 'Follow?', friendships_path(friend: @user), method: :post, class: "btn btn-info btn-sm" %></td>
    <% end %>
  </div>
</div>

<% if current_user.friends?(@user) %>
  <% if @tracked_stocks.present? %>
    <%= render 'stocks/tracked_list' %>
  <% else %>
    <p class="mt-4">This user is not currently tracking any stocks.</p>  
  <% end %>
<% else %>
  <p class="mt-4">Friend this user to see their tracked stocks.</p>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>